title: Test
description: Test page
theme: just-the-docs

url: https://ace.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout
